// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/hotspots/": {
            "get": {
                "description": "Retrieve a paginated list of raw hotspot detections.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hotspots"
                ],
                "summary": "List hotspots",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Max records to return (1-100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response-domain_GetHotspotsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/hotspots/filter-options": {
            "get": {
                "description": "Distinct confidence classes, satellite names, and products (NRT/SP) for filter dropdowns.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hotspots"
                ],
                "summary": "Filter options",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response-domain_GetFilterOptionsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/hotspots/geojson": {
            "get": {
                "description": "Retrieve hotspot detections as a GeoJSON FeatureCollection with cursor pagination. Supports date-range, time-period, location and product (NRT/SP) filters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hotspots"
                ],
                "summary": "Hotspots as GeoJSON",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (RFC3339)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (RFC3339)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by year",
                        "name": "year",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by semester",
                        "name": "semester",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by quarter",
                        "name": "quarter",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by month",
                        "name": "month",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by week",
                        "name": "week",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by province code",
                        "name": "province_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by city code",
                        "name": "city_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by district code",
                        "name": "district_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by subdistrict code",
                        "name": "subdistrict_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by satellite name",
                        "name": "satellite",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by confidence class",
                        "name": "confidence",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "NRT",
                            "SP"
                        ],
                        "type": "string",
                        "description": "Filter by product",
                        "name": "product",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Pagination cursor from previous page",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max features to return (1-50000, default 500)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response-domain_GeoJSON"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/hotspots/locations": {
            "get": {
                "description": "Drill-down geographic hierarchy with hotspot counts. Returns islands with grouped provinces at the top level, or cities/districts/subdistricts as the location code is drilled down.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hotspots"
                ],
                "summary": "Location hierarchy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Drill into this province",
                        "name": "province_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Drill into this city",
                        "name": "city_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Drill into this district",
                        "name": "district_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by satellite name",
                        "name": "satellite",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by confidence class",
                        "name": "confidence",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "NRT",
                            "SP"
                        ],
                        "type": "string",
                        "description": "Filter by product",
                        "name": "product",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date (RFC3339)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (RFC3339)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by year",
                        "name": "year",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by semester",
                        "name": "semester",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by quarter",
                        "name": "quarter",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by month",
                        "name": "month",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by week",
                        "name": "week",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response-domain_GetLocationsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/hotspots/periods": {
            "get": {
                "description": "Drill-down time period options (years then semesters, quarters, months, weeks) based on the params supplied.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hotspots"
                ],
                "summary": "Time period options",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Selected year",
                        "name": "year",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Selected semester",
                        "name": "semester",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Selected quarter",
                        "name": "quarter",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Selected month",
                        "name": "month",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response-domain_GetPeriodsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/hotspots/summary": {
            "get": {
                "description": "Aggregated dashboard summary: top provinces/cities, satellite and confidence distribution, overall stats, monthly stats and today's stats.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hotspots"
                ],
                "summary": "Dashboard summary",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Top provinces limit (1-100, default 10)",
                        "name": "province_limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Top cities limit (1-100, default 10)",
                        "name": "city_limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date (RFC3339)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (RFC3339)",
                        "name": "end_date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Response-domain_GetSummaryResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/domain.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.DistributionCount": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "domain.FilterOption": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.GeoJSON": {
            "type": "object",
            "properties": {
                "features": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.GeoJSONFeature"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/domain.Pagination"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.GeoJSONFeature": {
            "type": "object",
            "properties": {
                "geometry": {
                    "$ref": "#/definitions/domain.GeoJSONGeometry"
                },
                "properties": {
                    "$ref": "#/definitions/domain.GeoJSONFeatureProps"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.GeoJSONFeatureProps": {
            "type": "object",
            "properties": {
                "acquired_at": {
                    "type": "string"
                },
                "bright_t31": {
                    "type": "number"
                },
                "bright_ti4": {
                    "type": "number"
                },
                "bright_ti5": {
                    "type": "number"
                },
                "brightness": {
                    "type": "number"
                },
                "cloud_coverage": {
                    "type": "integer"
                },
                "confidence": {
                    "type": "string"
                },
                "confidence_class": {
                    "type": "string"
                },
                "frp": {
                    "type": "number"
                },
                "hotspot_count": {
                    "type": "integer"
                },
                "hotspot_time": {
                    "type": "string"
                },
                "humidity": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "instrument": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/domain.Location"
                },
                "precipitation": {
                    "type": "number"
                },
                "pressure": {
                    "type": "integer"
                },
                "product": {
                    "type": "string"
                },
                "satellite": {
                    "type": "string"
                },
                "satellite_name": {
                    "type": "string"
                },
                "solar_radiation": {
                    "type": "number"
                },
                "temperature": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                },
                "uv_index": {
                    "type": "integer"
                },
                "visibility": {
                    "type": "integer"
                },
                "weather_conditions": {
                    "type": "string"
                },
                "weather_icon": {
                    "type": "string"
                },
                "wind_degree": {
                    "type": "number"
                },
                "wind_speed": {
                    "type": "number"
                }
            }
        },
        "domain.GeoJSONGeometry": {
            "type": "object",
            "properties": {
                "coordinates": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.GetFilterOptionsResponse": {
            "type": "object",
            "properties": {
                "confidence": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.FilterOption"
                    }
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.FilterOption"
                    }
                },
                "satellites": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.FilterOption"
                    }
                }
            }
        },
        "domain.GetHotspotsResponse": {
            "type": "object",
            "properties": {
                "hotspots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.HotspotDetail"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/domain.Pagination"
                }
            }
        },
        "domain.GetLocationsResponse": {
            "type": "object",
            "properties": {
                "cities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.LocationHierarchyItem"
                    }
                },
                "districts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.LocationHierarchyItem"
                    }
                },
                "islands": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.IslandGroup"
                    }
                },
                "provinces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.LocationHierarchyItem"
                    }
                },
                "subdistricts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.LocationHierarchyItem"
                    }
                }
            }
        },
        "domain.GetPeriodsResponse": {
            "type": "object",
            "properties": {
                "months": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.PeriodValue"
                    }
                },
                "quarters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.PeriodValue"
                    }
                },
                "semesters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.PeriodValue"
                    }
                },
                "weeks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.PeriodValue"
                    }
                },
                "years": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.PeriodValue"
                    }
                }
            }
        },
        "domain.GetStatsResponse": {
            "type": "object",
            "properties": {
                "affected_provinces": {
                    "type": "integer"
                },
                "high_confidence": {
                    "type": "integer"
                },
                "total_hotspots": {
                    "type": "integer"
                }
            }
        },
        "domain.GetSummaryResponse": {
            "type": "object",
            "properties": {
                "confidence_distribution": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.DistributionCount"
                    }
                },
                "monthly_stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.MonthlyStats"
                    }
                },
                "satellite_distribution": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.DistributionCount"
                    }
                },
                "stats": {
                    "$ref": "#/definitions/domain.GetStatsResponse"
                },
                "today_stats": {
                    "$ref": "#/definitions/domain.GetTodayStatsResponse"
                },
                "top_cities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.LocationCount"
                    }
                },
                "top_provinces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.LocationCount"
                    }
                }
            }
        },
        "domain.GetTodayStatsResponse": {
            "type": "object",
            "properties": {
                "today_affected_provinces": {
                    "type": "integer"
                },
                "today_high_confidence": {
                    "type": "integer"
                },
                "today_hotspots": {
                    "type": "integer"
                }
            }
        },
        "domain.HotspotDetail": {
            "type": "object",
            "properties": {
                "acquired_at": {
                    "type": "string"
                },
                "bright_t31": {
                    "type": "number"
                },
                "bright_ti4": {
                    "type": "number"
                },
                "bright_ti5": {
                    "type": "number"
                },
                "brightness": {
                    "type": "number"
                },
                "city_code": {
                    "type": "string"
                },
                "city_name": {
                    "type": "string"
                },
                "cloud_coverage": {
                    "type": "integer"
                },
                "confidence_class": {
                    "type": "string"
                },
                "district_code": {
                    "type": "string"
                },
                "district_name": {
                    "type": "string"
                },
                "frp": {
                    "type": "number"
                },
                "humidity": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "latitude": {
                    "type": "string"
                },
                "longitude": {
                    "type": "string"
                },
                "precipitation": {
                    "type": "number"
                },
                "pressure": {
                    "type": "integer"
                },
                "product": {
                    "type": "string"
                },
                "province_code": {
                    "type": "string"
                },
                "province_name": {
                    "type": "string"
                },
                "satellite_name": {
                    "type": "string"
                },
                "solar_radiation": {
                    "type": "number"
                },
                "subdistrict_code": {
                    "type": "string"
                },
                "subdistrict_name": {
                    "type": "string"
                },
                "temperature": {
                    "type": "integer"
                },
                "uv_index": {
                    "type": "integer"
                },
                "visibility": {
                    "type": "integer"
                },
                "weather_conditions": {
                    "type": "string"
                },
                "weather_icon": {
                    "type": "string"
                },
                "wind_degree": {
                    "type": "number"
                },
                "wind_speed": {
                    "type": "number"
                }
            }
        },
        "domain.IslandGroup": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "provinces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.LocationHierarchyItem"
                    }
                }
            }
        },
        "domain.Location": {
            "type": "object",
            "properties": {
                "city_name": {
                    "type": "string"
                },
                "desa": {
                    "type": "string"
                },
                "district_name": {
                    "type": "string"
                },
                "kab_kota": {
                    "type": "string"
                },
                "kecamatan": {
                    "type": "string"
                },
                "province_name": {
                    "type": "string"
                },
                "provinsi": {
                    "type": "string"
                },
                "pulau": {
                    "type": "string"
                },
                "subdistrict_name": {
                    "type": "string"
                }
            }
        },
        "domain.LocationCount": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.LocationHierarchyItem": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "pulau": {
                    "type": "string"
                }
            }
        },
        "domain.MonthlyStats": {
            "type": "object",
            "properties": {
                "high_confidence": {
                    "type": "integer"
                },
                "month": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "domain.Pagination": {
            "type": "object",
            "properties": {
                "has_next": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "next_cursor": {
                    "type": "string"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "domain.PeriodValue": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "domain.Response-domain_GeoJSON": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.GeoJSON"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "domain.Response-domain_GetFilterOptionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.GetFilterOptionsResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "domain.Response-domain_GetHotspotsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.GetHotspotsResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "domain.Response-domain_GetLocationsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.GetLocationsResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "domain.Response-domain_GetPeriodsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.GetPeriodsResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "domain.Response-domain_GetSummaryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.GetSummaryResponse"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Hotspot API",
	Description:      "REST API for Indonesia wildfire hotspot analytics (detections, GeoJSON, summary, drill-down locations and periods).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
