x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: infra/airflow/Dockerfile
  platform: linux/amd64
  env_file:
    - .env
  volumes:
    - ./infra/airflow/dags:/opt/airflow/dags
    - ./infra/airflow/plugins:/opt/airflow/plugins
    - ./src:/opt/airflow/src
    - ./pyproject.toml:/opt/airflow/pyproject.toml
  depends_on:
    - postgres
    - redis
  restart: always

services:
  postgres:
    image: postgres:18.0
    command: postgres -N ${POSTGRES_MAX_CONN}
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - 127.0.0.1:${AIRFLOW_WEB_PORT}:8080

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      _AIRFLOW_DB_MIGRATE: ${AIRFLOW_DB_MIGRATE}
      _AIRFLOW_WWW_USER_CREATE: ${_AIRFLOW_WWW_USER_CREATE}
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_WEB_DEFAULT_USER}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_WEB_DEFAULT_PASSWORD}

  redis:
    image: redis:8.0
    ports:
      - 127.0.0.1:${REDIS_PORT:-6379}:6379
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:24.5.1
    platform: linux/amd64
    ports:
      - 127.0.0.1:${CLICKHOUSE_PORT}:8123
      - 127.0.0.1:${CLICKHOUSE_NATIVE_PORT:-9000}:9000
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-hotspot}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  postgres-data:
  clickhouse-data:
  redis-data:
