// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/zsbahtiar/hotspot/api/domain"
)

// NewHotspotRepository creates a new instance of HotspotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHotspotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *HotspotRepository {
	mock := &HotspotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HotspotRepository is an autogenerated mock type for the HotspotRepository type
type HotspotRepository struct {
	mock.Mock
}

type HotspotRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *HotspotRepository) EXPECT() *HotspotRepository_Expecter {
	return &HotspotRepository_Expecter{mock: &_m.Mock}
}

// GetConfidenceDistribution provides a mock function for the type HotspotRepository
func (_mock *HotspotRepository) GetConfidenceDistribution(ctx context.Context, req domain.GetDistributionRequest) ([]domain.DistributionCount, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetConfidenceDistribution")
	}

	var r0 []domain.DistributionCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetDistributionRequest) ([]domain.DistributionCount, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetDistributionRequest) []domain.DistributionCount); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DistributionCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.GetDistributionRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HotspotRepository_GetConfidenceDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfidenceDistribution'
type HotspotRepository_GetConfidenceDistribution_Call struct {
	*mock.Call
}

// GetConfidenceDistribution is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.GetDistributionRequest
func (_e *HotspotRepository_Expecter) GetConfidenceDistribution(ctx interface{}, req interface{}) *HotspotRepository_GetConfidenceDistribution_Call {
	return &HotspotRepository_GetConfidenceDistribution_Call{Call: _e.mock.On("GetConfidenceDistribution", ctx, req)}
}

func (_c *HotspotRepository_GetConfidenceDistribution_Call) Run(run func(ctx context.Context, req domain.GetDistributionRequest)) *HotspotRepository_GetConfidenceDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.GetDistributionRequest
		if args[1] != nil {
			arg1 = args[1].(domain.GetDistributionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HotspotRepository_GetConfidenceDistribution_Call) Return(distributionCounts []domain.DistributionCount, err error) *HotspotRepository_GetConfidenceDistribution_Call {
	_c.Call.Return(distributionCounts, err)
	return _c
}

func (_c *HotspotRepository_GetConfidenceDistribution_Call) RunAndReturn(run func(ctx context.Context, req domain.GetDistributionRequest) ([]domain.DistributionCount, error)) *HotspotRepository_GetConfidenceDistribution_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfidenceList provides a mock function for the type HotspotRepository
func (_mock *HotspotRepository) GetConfidenceList(ctx context.Context) ([]domain.FilterOption, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConfidenceList")
	}

	var r0 []domain.FilterOption
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.FilterOption, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.FilterOption); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FilterOption)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HotspotRepository_GetConfidenceList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfidenceList'
type HotspotRepository_GetConfidenceList_Call struct {
	*mock.Call
}

// GetConfidenceList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HotspotRepository_Expecter) GetConfidenceList(ctx interface{}) *HotspotRepository_GetConfidenceList_Call {
	return &HotspotRepository_GetConfidenceList_Call{Call: _e.mock.On("GetConfidenceList", ctx)}
}

func (_c *HotspotRepository_GetConfidenceList_Call) Run(run func(ctx context.Context)) *HotspotRepository_GetConfidenceList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HotspotRepository_GetConfidenceList_Call) Return(filterOptions []domain.FilterOption, err error) *HotspotRepository_GetConfidenceList_Call {
	_c.Call.Return(filterOptions, err)
	return _c
}

func (_c *HotspotRepository_GetConfidenceList_Call) RunAndReturn(run func(ctx context.Context) ([]domain.FilterOption, error)) *HotspotRepository_GetConfidenceList_Call {
	_c.Call.Return(run)
	return _c
}

// GetHotspots provides a mock function for the type HotspotRepository
func (_mock *HotspotRepository) GetHotspots(ctx context.Context, req domain.GetHotspotsRequest) (*domain.GetHotspotsResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetHotspots")
	}

	var r0 *domain.GetHotspotsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetHotspotsRequest) (*domain.GetHotspotsResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetHotspotsRequest) *domain.GetHotspotsResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetHotspotsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.GetHotspotsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HotspotRepository_GetHotspots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHotspots'
type HotspotRepository_GetHotspots_Call struct {
	*mock.Call
}

// GetHotspots is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.GetHotspotsRequest
func (_e *HotspotRepository_Expecter) GetHotspots(ctx interface{}, req interface{}) *HotspotRepository_GetHotspots_Call {
	return &HotspotRepository_GetHotspots_Call{Call: _e.mock.On("GetHotspots", ctx, req)}
}

func (_c *HotspotRepository_GetHotspots_Call) Run(run func(ctx context.Context, req domain.GetHotspotsRequest)) *HotspotRepository_GetHotspots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.GetHotspotsRequest
		if args[1] != nil {
			arg1 = args[1].(domain.GetHotspotsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HotspotRepository_GetHotspots_Call) Return(getHotspotsResponse *domain.GetHotspotsResponse, err error) *HotspotRepository_GetHotspots_Call {
	_c.Call.Return(getHotspotsResponse, err)
	return _c
}

func (_c *HotspotRepository_GetHotspots_Call) RunAndReturn(run func(ctx context.Context, req domain.GetHotspotsRequest) (*domain.GetHotspotsResponse, error)) *HotspotRepository_GetHotspots_Call {
	_c.Call.Return(run)
	return _c
}

// GetLocations provides a mock function for the type HotspotRepository
func (_mock *HotspotRepository) GetLocations(ctx context.Context, req domain.GetLocationsRequest) (*domain.GetLocationsResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetLocations")
	}

	var r0 *domain.GetLocationsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetLocationsRequest) (*domain.GetLocationsResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetLocationsRequest) *domain.GetLocationsResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetLocationsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.GetLocationsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HotspotRepository_GetLocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLocations'
type HotspotRepository_GetLocations_Call struct {
	*mock.Call
}

// GetLocations is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.GetLocationsRequest
func (_e *HotspotRepository_Expecter) GetLocations(ctx interface{}, req interface{}) *HotspotRepository_GetLocations_Call {
	return &HotspotRepository_GetLocations_Call{Call: _e.mock.On("GetLocations", ctx, req)}
}

func (_c *HotspotRepository_GetLocations_Call) Run(run func(ctx context.Context, req domain.GetLocationsRequest)) *HotspotRepository_GetLocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.GetLocationsRequest
		if args[1] != nil {
			arg1 = args[1].(domain.GetLocationsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HotspotRepository_GetLocations_Call) Return(getLocationsResponse *domain.GetLocationsResponse, err error) *HotspotRepository_GetLocations_Call {
	_c.Call.Return(getLocationsResponse, err)
	return _c
}

func (_c *HotspotRepository_GetLocations_Call) RunAndReturn(run func(ctx context.Context, req domain.GetLocationsRequest) (*domain.GetLocationsResponse, error)) *HotspotRepository_GetLocations_Call {
	_c.Call.Return(run)
	return _c
}

// GetMonthlyStats provides a mock function for the type HotspotRepository
func (_mock *HotspotRepository) GetMonthlyStats(ctx context.Context, req domain.GetMonthlyStatsRequest) ([]domain.MonthlyStats, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetMonthlyStats")
	}

	var r0 []domain.MonthlyStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetMonthlyStatsRequest) ([]domain.MonthlyStats, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetMonthlyStatsRequest) []domain.MonthlyStats); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MonthlyStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.GetMonthlyStatsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HotspotRepository_GetMonthlyStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonthlyStats'
type HotspotRepository_GetMonthlyStats_Call struct {
	*mock.Call
}

// GetMonthlyStats is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.GetMonthlyStatsRequest
func (_e *HotspotRepository_Expecter) GetMonthlyStats(ctx interface{}, req interface{}) *HotspotRepository_GetMonthlyStats_Call {
	return &HotspotRepository_GetMonthlyStats_Call{Call: _e.mock.On("GetMonthlyStats", ctx, req)}
}

func (_c *HotspotRepository_GetMonthlyStats_Call) Run(run func(ctx context.Context, req domain.GetMonthlyStatsRequest)) *HotspotRepository_GetMonthlyStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.GetMonthlyStatsRequest
		if args[1] != nil {
			arg1 = args[1].(domain.GetMonthlyStatsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HotspotRepository_GetMonthlyStats_Call) Return(monthlyStatss []domain.MonthlyStats, err error) *HotspotRepository_GetMonthlyStats_Call {
	_c.Call.Return(monthlyStatss, err)
	return _c
}

func (_c *HotspotRepository_GetMonthlyStats_Call) RunAndReturn(run func(ctx context.Context, req domain.GetMonthlyStatsRequest) ([]domain.MonthlyStats, error)) *HotspotRepository_GetMonthlyStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetPeriods provides a mock function for the type HotspotRepository
func (_mock *HotspotRepository) GetPeriods(ctx context.Context, req domain.GetPeriodsRequest) (*domain.GetPeriodsResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetPeriods")
	}

	var r0 *domain.GetPeriodsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetPeriodsRequest) (*domain.GetPeriodsResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetPeriodsRequest) *domain.GetPeriodsResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetPeriodsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.GetPeriodsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HotspotRepository_GetPeriods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPeriods'
type HotspotRepository_GetPeriods_Call struct {
	*mock.Call
}

// GetPeriods is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.GetPeriodsRequest
func (_e *HotspotRepository_Expecter) GetPeriods(ctx interface{}, req interface{}) *HotspotRepository_GetPeriods_Call {
	return &HotspotRepository_GetPeriods_Call{Call: _e.mock.On("GetPeriods", ctx, req)}
}

func (_c *HotspotRepository_GetPeriods_Call) Run(run func(ctx context.Context, req domain.GetPeriodsRequest)) *HotspotRepository_GetPeriods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.GetPeriodsRequest
		if args[1] != nil {
			arg1 = args[1].(domain.GetPeriodsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HotspotRepository_GetPeriods_Call) Return(getPeriodsResponse *domain.GetPeriodsResponse, err error) *HotspotRepository_GetPeriods_Call {
	_c.Call.Return(getPeriodsResponse, err)
	return _c
}

func (_c *HotspotRepository_GetPeriods_Call) RunAndReturn(run func(ctx context.Context, req domain.GetPeriodsRequest) (*domain.GetPeriodsResponse, error)) *HotspotRepository_GetPeriods_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductList provides a mock function for the type HotspotRepository
func (_mock *HotspotRepository) GetProductList(ctx context.Context) ([]domain.FilterOption, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetProductList")
	}

	var r0 []domain.FilterOption
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.FilterOption, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.FilterOption); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FilterOption)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HotspotRepository_GetProductList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductList'
type HotspotRepository_GetProductList_Call struct {
	*mock.Call
}

// GetProductList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HotspotRepository_Expecter) GetProductList(ctx interface{}) *HotspotRepository_GetProductList_Call {
	return &HotspotRepository_GetProductList_Call{Call: _e.mock.On("GetProductList", ctx)}
}

func (_c *HotspotRepository_GetProductList_Call) Run(run func(ctx context.Context)) *HotspotRepository_GetProductList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HotspotRepository_GetProductList_Call) Return(filterOptions []domain.FilterOption, err error) *HotspotRepository_GetProductList_Call {
	_c.Call.Return(filterOptions, err)
	return _c
}

func (_c *HotspotRepository_GetProductList_Call) RunAndReturn(run func(ctx context.Context) ([]domain.FilterOption, error)) *HotspotRepository_GetProductList_Call {
	_c.Call.Return(run)
	return _c
}

// GetSatelliteDistribution provides a mock function for the type HotspotRepository
func (_mock *HotspotRepository) GetSatelliteDistribution(ctx context.Context, req domain.GetDistributionRequest) ([]domain.DistributionCount, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetSatelliteDistribution")
	}

	var r0 []domain.DistributionCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetDistributionRequest) ([]domain.DistributionCount, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetDistributionRequest) []domain.DistributionCount); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DistributionCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.GetDistributionRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HotspotRepository_GetSatelliteDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSatelliteDistribution'
type HotspotRepository_GetSatelliteDistribution_Call struct {
	*mock.Call
}

// GetSatelliteDistribution is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.GetDistributionRequest
func (_e *HotspotRepository_Expecter) GetSatelliteDistribution(ctx interface{}, req interface{}) *HotspotRepository_GetSatelliteDistribution_Call {
	return &HotspotRepository_GetSatelliteDistribution_Call{Call: _e.mock.On("GetSatelliteDistribution", ctx, req)}
}

func (_c *HotspotRepository_GetSatelliteDistribution_Call) Run(run func(ctx context.Context, req domain.GetDistributionRequest)) *HotspotRepository_GetSatelliteDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.GetDistributionRequest
		if args[1] != nil {
			arg1 = args[1].(domain.GetDistributionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HotspotRepository_GetSatelliteDistribution_Call) Return(distributionCounts []domain.DistributionCount, err error) *HotspotRepository_GetSatelliteDistribution_Call {
	_c.Call.Return(distributionCounts, err)
	return _c
}

func (_c *HotspotRepository_GetSatelliteDistribution_Call) RunAndReturn(run func(ctx context.Context, req domain.GetDistributionRequest) ([]domain.DistributionCount, error)) *HotspotRepository_GetSatelliteDistribution_Call {
	_c.Call.Return(run)
	return _c
}

// GetSatelliteList provides a mock function for the type HotspotRepository
func (_mock *HotspotRepository) GetSatelliteList(ctx context.Context) ([]domain.FilterOption, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSatelliteList")
	}

	var r0 []domain.FilterOption
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.FilterOption, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.FilterOption); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FilterOption)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HotspotRepository_GetSatelliteList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSatelliteList'
type HotspotRepository_GetSatelliteList_Call struct {
	*mock.Call
}

// GetSatelliteList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HotspotRepository_Expecter) GetSatelliteList(ctx interface{}) *HotspotRepository_GetSatelliteList_Call {
	return &HotspotRepository_GetSatelliteList_Call{Call: _e.mock.On("GetSatelliteList", ctx)}
}

func (_c *HotspotRepository_GetSatelliteList_Call) Run(run func(ctx context.Context)) *HotspotRepository_GetSatelliteList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HotspotRepository_GetSatelliteList_Call) Return(filterOptions []domain.FilterOption, err error) *HotspotRepository_GetSatelliteList_Call {
	_c.Call.Return(filterOptions, err)
	return _c
}

func (_c *HotspotRepository_GetSatelliteList_Call) RunAndReturn(run func(ctx context.Context) ([]domain.FilterOption, error)) *HotspotRepository_GetSatelliteList_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function for the type HotspotRepository
func (_mock *HotspotRepository) GetStats(ctx context.Context, req domain.GetStatsRequest) (*domain.GetStatsResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *domain.GetStatsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetStatsRequest) (*domain.GetStatsResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetStatsRequest) *domain.GetStatsResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetStatsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.GetStatsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HotspotRepository_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type HotspotRepository_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.GetStatsRequest
func (_e *HotspotRepository_Expecter) GetStats(ctx interface{}, req interface{}) *HotspotRepository_GetStats_Call {
	return &HotspotRepository_GetStats_Call{Call: _e.mock.On("GetStats", ctx, req)}
}

func (_c *HotspotRepository_GetStats_Call) Run(run func(ctx context.Context, req domain.GetStatsRequest)) *HotspotRepository_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.GetStatsRequest
		if args[1] != nil {
			arg1 = args[1].(domain.GetStatsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HotspotRepository_GetStats_Call) Return(getStatsResponse *domain.GetStatsResponse, err error) *HotspotRepository_GetStats_Call {
	_c.Call.Return(getStatsResponse, err)
	return _c
}

func (_c *HotspotRepository_GetStats_Call) RunAndReturn(run func(ctx context.Context, req domain.GetStatsRequest) (*domain.GetStatsResponse, error)) *HotspotRepository_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodayStats provides a mock function for the type HotspotRepository
func (_mock *HotspotRepository) GetTodayStats(ctx context.Context, timezone string) (*domain.GetTodayStatsResponse, error) {
	ret := _mock.Called(ctx, timezone)

	if len(ret) == 0 {
		panic("no return value specified for GetTodayStats")
	}

	var r0 *domain.GetTodayStatsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.GetTodayStatsResponse, error)); ok {
		return returnFunc(ctx, timezone)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.GetTodayStatsResponse); ok {
		r0 = returnFunc(ctx, timezone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetTodayStatsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, timezone)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HotspotRepository_GetTodayStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodayStats'
type HotspotRepository_GetTodayStats_Call struct {
	*mock.Call
}

// GetTodayStats is a helper method to define mock.On call
//   - ctx context.Context
//   - timezone string
func (_e *HotspotRepository_Expecter) GetTodayStats(ctx interface{}, timezone interface{}) *HotspotRepository_GetTodayStats_Call {
	return &HotspotRepository_GetTodayStats_Call{Call: _e.mock.On("GetTodayStats", ctx, timezone)}
}

func (_c *HotspotRepository_GetTodayStats_Call) Run(run func(ctx context.Context, timezone string)) *HotspotRepository_GetTodayStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HotspotRepository_GetTodayStats_Call) Return(getTodayStatsResponse *domain.GetTodayStatsResponse, err error) *HotspotRepository_GetTodayStats_Call {
	_c.Call.Return(getTodayStatsResponse, err)
	return _c
}

func (_c *HotspotRepository_GetTodayStats_Call) RunAndReturn(run func(ctx context.Context, timezone string) (*domain.GetTodayStatsResponse, error)) *HotspotRepository_GetTodayStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopCities provides a mock function for the type HotspotRepository
func (_mock *HotspotRepository) GetTopCities(ctx context.Context, req domain.GetTopCityRequest) ([]domain.LocationCount, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetTopCities")
	}

	var r0 []domain.LocationCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetTopCityRequest) ([]domain.LocationCount, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetTopCityRequest) []domain.LocationCount); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.LocationCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.GetTopCityRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HotspotRepository_GetTopCities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopCities'
type HotspotRepository_GetTopCities_Call struct {
	*mock.Call
}

// GetTopCities is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.GetTopCityRequest
func (_e *HotspotRepository_Expecter) GetTopCities(ctx interface{}, req interface{}) *HotspotRepository_GetTopCities_Call {
	return &HotspotRepository_GetTopCities_Call{Call: _e.mock.On("GetTopCities", ctx, req)}
}

func (_c *HotspotRepository_GetTopCities_Call) Run(run func(ctx context.Context, req domain.GetTopCityRequest)) *HotspotRepository_GetTopCities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.GetTopCityRequest
		if args[1] != nil {
			arg1 = args[1].(domain.GetTopCityRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HotspotRepository_GetTopCities_Call) Return(locationCounts []domain.LocationCount, err error) *HotspotRepository_GetTopCities_Call {
	_c.Call.Return(locationCounts, err)
	return _c
}

func (_c *HotspotRepository_GetTopCities_Call) RunAndReturn(run func(ctx context.Context, req domain.GetTopCityRequest) ([]domain.LocationCount, error)) *HotspotRepository_GetTopCities_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopProvinces provides a mock function for the type HotspotRepository
func (_mock *HotspotRepository) GetTopProvinces(ctx context.Context, req domain.GetTopProvincesRequest) ([]domain.LocationCount, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetTopProvinces")
	}

	var r0 []domain.LocationCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetTopProvincesRequest) ([]domain.LocationCount, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.GetTopProvincesRequest) []domain.LocationCount); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.LocationCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.GetTopProvincesRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HotspotRepository_GetTopProvinces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopProvinces'
type HotspotRepository_GetTopProvinces_Call struct {
	*mock.Call
}

// GetTopProvinces is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.GetTopProvincesRequest
func (_e *HotspotRepository_Expecter) GetTopProvinces(ctx interface{}, req interface{}) *HotspotRepository_GetTopProvinces_Call {
	return &HotspotRepository_GetTopProvinces_Call{Call: _e.mock.On("GetTopProvinces", ctx, req)}
}

func (_c *HotspotRepository_GetTopProvinces_Call) Run(run func(ctx context.Context, req domain.GetTopProvincesRequest)) *HotspotRepository_GetTopProvinces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.GetTopProvincesRequest
		if args[1] != nil {
			arg1 = args[1].(domain.GetTopProvincesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HotspotRepository_GetTopProvinces_Call) Return(locationCounts []domain.LocationCount, err error) *HotspotRepository_GetTopProvinces_Call {
	_c.Call.Return(locationCounts, err)
	return _c
}

func (_c *HotspotRepository_GetTopProvinces_Call) RunAndReturn(run func(ctx context.Context, req domain.GetTopProvincesRequest) ([]domain.LocationCount, error)) *HotspotRepository_GetTopProvinces_Call {
	_c.Call.Return(run)
	return _c
}
